from pymongo import MongoClient
from pymongo.server_api import ServerApi
import certifi
from dotenv import load_dotenv
import os
load_dotenv()

# MongoDB 연결
uri = os.getenv('MONGODB_URI')
client = MongoClient(uri, tlsCAFile=certifi.where())
db = client["korea_regions_db"]
# -*- coding: utf-8 -*-
"""stations with normalized admin suffixes (시/군/구/읍/면/리/동) and metro names.
"""
data = {'강원도': [{'code': 90, 'name': '속초시'},
           {'code': 95, 'name': '철원군'},
           {'code': 101, 'name': '춘천시'},
           {'code': 105, 'name': '강릉시'},
           {'code': 106, 'name': '동해시'},
           {'code': 114, 'name': '원주시'},
           {'code': 121, 'name': '영월군'},
           {'code': 211, 'name': '인제군'},
           {'code': 212, 'name': '홍천군'},
           {'code': 216, 'name': '태백시'},
           {'code': 217, 'name': '정선군'},
           {'code': 526, 'name': '평창군'},
           {'code': 536, 'name': '횡성군'},
           {'code': 555, 'name': '화천군'},
           {'code': 670, 'name': '양양군'},
           {'code': 876, 'name': '삼척시'}],
 '경기도': [{'code': 98, 'name': '동두천시'},
          {'code': 99, 'name': '파주시'},
          {'code': 119, 'name': '수원시'},
          {'code': 202, 'name': '양평군'},
          {'code': 203, 'name': '이천시'},
          {'code': 364, 'name': '분당구'},
          {'code': 433, 'name': '부천시'},
          {'code': 434, 'name': '안양시'},
          {'code': 437, 'name': '광명시'},
          {'code': 438, 'name': '군포시'},
          {'code': 441, 'name': '김포시'},
          {'code': 444, 'name': '하남시'},
          {'code': 445, 'name': '의왕시'},
          {'code': 456, 'name': '연천군'},
          {'code': 504, 'name': '포천시'},
          {'code': 516, 'name': '안성시'},
          {'code': 532, 'name': '의정부시'},
          {'code': 540, 'name': '고양시'},
          {'code': 541, 'name': '남양주시'},
          {'code': 548, 'name': '여주시'},
          {'code': 549, 'name': '용인시'},
          {'code': 551, 'name': '평택시'},
          {'code': 565, 'name': '시흥시'},
          {'code': 572, 'name': '성남시'},
          {'code': 590, 'name': '과천시'},
          {'code': 598, 'name': '양주시'}],
 '경상남도': [{'code': 155, 'name': '창원시'},
           {'code': 162, 'name': '통영시'},
           {'code': 192, 'name': '진주시'},
           {'code': 253, 'name': '김해시'},
           {'code': 257, 'name': '양산시'},
           {'code': 263, 'name': '의령군'},
           {'code': 264, 'name': '함양군'},
           {'code': 284, 'name': '거창군'},
           {'code': 285, 'name': '합천군'},
           {'code': 288, 'name': '밀양시'},
           {'code': 289, 'name': '산청군'},
           {'code': 294, 'name': '거제시'},
           {'code': 295, 'name': '남해군'},
           {'code': 917, 'name': '사천시'},
           {'code': 918, 'name': '고성군'},
           {'code': 919, 'name': '창녕군'},
           {'code': 920, 'name': '함안군'}],
 '경상북도': [{'code': 130, 'name': '울진군'},
           {'code': 137, 'name': '상주시'},
           {'code': 272, 'name': '영주시'},
           {'code': 273, 'name': '문경시'},
           {'code': 276, 'name': '청송군'},
           {'code': 277, 'name': '영덕군'},
           {'code': 278, 'name': '의성군'},
           {'code': 279, 'name': '구미시'},
           {'code': 281, 'name': '영천시'},
           {'code': 283, 'name': '경주시'},
           {'code': 801, 'name': '영양군'},
           {'code': 810, 'name': '성주군'},
           {'code': 812, 'name': '고령군'},
           {'code': 822, 'name': '김천시'},
           {'code': 823, 'name': '군위군'},
           {'code': 825, 'name': '칠곡군'},
           {'code': 115, 'name': '울릉군'},
           {'code' : 96, 'name': '독도'}],
 '광주광역시': [{'code': 156, 'name': '광주광역시'},
            {'code': 689, 'name': '광주남구'},
            {'code': 708, 'name': '광산구'}],
 '대구광역시': [{'code': 143, 'name': '대구광역시'},
            {'code': 845, 'name': '대구북구'},
            {'code': 846, 'name': '대구서구'},
            {'code': 860, 'name': '신암동'}],
 '대전광역시': [{'code': 133, 'name': '대전광역시'},
            {'code': 630, 'name': '노은동'},
            {'code': 643, 'name': '세천동'}],
 '부산광역시': [{'code': 159, 'name': '부산광역시'},
            {'code': 160, 'name': '부산광역시'},
            {'code': 904, 'name': '사상구'},
            {'code': 923, 'name': '기장군'},
            {'code': 937, 'name': '해운대구'},
            {'code': 938, 'name': '부산진구'},
            {'code': 939, 'name': '금정구'},
            {'code': 940, 'name': '동래구'},
            {'code': 941, 'name': '북구'},
            {'code': 942, 'name': '부산남구'},
            {'code': 950, 'name': '사하구'}],
 '서울특별시': [{'code': 108, 'name': '서울특별시'},
            {'code': 116, 'name': '관악구'},
            {'code': 400, 'name': '강남구'},
            {'code': 401, 'name': '서초구'},
            {'code': 402, 'name': '강동구'},
            {'code': 403, 'name': '송파구'},
            {'code': 404, 'name': '강서구'},
            {'code': 405, 'name': '양천구'},
            {'code': 407, 'name': '노원구'},
            {'code': 408, 'name': '동대문구'},
            {'code': 409, 'name': '중랑구'},
            {'code': 411, 'name': '마포구'},
            {'code': 412, 'name': '서대문구'},
            {'code': 413, 'name': '광진구'},
            {'code': 414, 'name': '성북구'},
            {'code': 416, 'name': '은평구'},
            {'code': 417, 'name': '금천구'},
            {'code': 419, 'name': '중구'},
            {'code': 421, 'name': '성동구'},
            {'code': 423, 'name': '구로구'},
            {'code': 424, 'name': '강북구'},
            {'code': 425, 'name': '남현동'},
            {'code': 509, 'name': '관악구'},
            {'code': 510, 'name': '영등포구'}],
 '세종특별자치시': [{'code': 239, 'name': '세종특별자치시'},
        {'code': 495, 'name': '고운동'},   
        {'code': 497, 'name': '금남면'},  
    {'code': 612, 'name': '연서면'},   
    {'code': 630, 'name': '전의면'}
    ],
 '울산광역시': [{'code': 898, 'name': '장생포동'}],
 '인천광역시': [{'code': 112, 'name': '인천광역시'}, {'code': 511, 'name': '경서동'}],
 '전라남도': [{'code': 165, 'name': '목포시'},
           {'code': 168, 'name': '여수시'},
           {'code': 174, 'name': '순천시'},
           {'code': 175, 'name': '진도군'},
           {'code': 252, 'name': '영광군'},
           {'code': 258, 'name': '보성군'},
           {'code': 259, 'name': '강진군'},
           {'code': 260, 'name': '장흥군'},
           {'code': 261, 'name': '해남군'},
           {'code': 262, 'name': '고흥군'},
           {'code': 266, 'name': '광양시'},
           {'code': 268, 'name': '진도군'},
           {'code': 699, 'name': '무안군'},
           {'code': 706, 'name': '담양군'},
           {'code': 709, 'name': '구례군'},
           {'code': 710, 'name': '나주시'},
           {'code': 712, 'name': '순천시'},
           {'code': 730, 'name': '장성군'},
           {'code': 731, 'name': '영암군'},
           {'code': 732, 'name': '보성군'},
           {'code': 741, 'name': '화순군'},
           {'code': 754, 'name': '함평군'},
           {'code': 768, 'name': '곡성군'}],
 '전라북도': [{'code': 146, 'name': '전주시'},
           {'code': 172, 'name': '고창군'},
           {'code': 243, 'name': '부안군'},
           {'code': 244, 'name': '임실군'},
           {'code': 247, 'name': '남원시'},
           {'code': 248, 'name': '장수군'},
           {'code': 251, 'name': '고창군'},
           {'code': 254, 'name': '순창군'},
           {'code': 439, 'name': '진안군'},
           {'code': 701, 'name': '무주군'},
           {'code': 703, 'name': '진안군'},
           {'code': 734, 'name': '완주군'},
           {'code': 737, 'name': '김제시'}],
 '제주특별자치도': [{'code': 184, 'name': '제주시'}, {'code': 189, 'name': '서귀포시'}],
 '충청남도': [{'code': 177, 'name': '홍성군'},
           {'code': 232, 'name': '천안시'},
           {'code': 235, 'name': '보령시'},
           {'code': 612, 'name': '공주시'},
           {'code': 614, 'name': '서천군'},
           {'code': 616, 'name': '당진시'},
           {'code': 618, 'name': '청양군'},
           {'code': 627, 'name': '태안군'},
           {'code': 632, 'name': '유구'},
           {'code': 636, 'name': '계룡시'}],
 '충청북도': [{'code': 127, 'name': '충주시'},
           {'code': 131, 'name': '청주시'},
           {'code': 221, 'name': '제천시'},
           {'code': 226, 'name': '보은군'},
           {'code': 449, 'name': '옥천군'},
           {'code': 601, 'name': '단양군'},
           {'code': 602, 'name': '진천군'},
           {'code': 604, 'name': '옥천군'},
           {'code': 619, 'name': '음성군'},
           {'code': 623, 'name': '증평군'}]}
for province, regions in data.items():
    # 컬렉션 이름 = 광역시/도 이름
    collection = db[province]
    
    # 기존 데이터 삭제 (중복 방지)
    # collection.delete_many({})
    
    # 각 지역을 하나씩 문서로 삽입
    for region in regions:
        collection.insert_one({**region, 'hot': [0,0,0,0,0,0], 'normal': [0,0,0,0,0,0], 'cold': [0,0,0,0,0,0]})

print("모든 광역시/도별 컬렉션에 데이터 삽입 완료!")